### ISSUE TITLE
주제 및 기능 명세서 작성

### ISSUE THREAD

**Issue by astrataraxia** [weble4/linked-house-backend#1]
주제 선정 및 예상 기능들을 작성하고, 프로젝트 준비를 하는 단계

- [x] 주제 선정
   -  여행, 숙박과 관련된 주제 선정
- [ ] 기능 설계
   - 기능설계 명세서, 메뉴 테이블 작성

**Comment by Letyon** [comment]
명세서 confirm 완료, 보완할 내용 확인 후 진행중
